import { FormEvent, useState } from 'react'

type Language = 'en' | 'ka' | 'ru' | 'es'
type Props = { language: Language; onTripCreated?: () => void }
const choices = [
  ['What would you rather do?', ['Explore at my pace', 'See the highlights']],
  ['When do you like to go out?', ['Early morning', 'Morning to evening', 'Late afternoon & night']],
  ['Who should this day feel like?', ['Meet locals', 'A quiet day for myself']],
] as const
const costs: Record<string, number> = { Food: 35, History: 18, Nature: 22, Art: 28, Nightlife: 42, Wellness: 38 }
const labels = { en: { title: 'Build a trip around you', lead: 'Tell Compass what you enjoy and it will shape a realistic day.', country: 'Country', city: 'City', interests: 'Choose your interests', budget: 'Daily budget (USD)', next: 'Next question', back: 'Back', make: 'Create my route', picks: 'Your first-day picks' }, ka: { title: 'შექმენი შენზე მორგებული მოგზაურობა', lead: 'მოგვიყევი ინტერესების შესახებ და Compass შექმნის რეალისტურ მარშრუტს.', country: 'ქვეყანა', city: 'ქალაქი', interests: 'აირჩიე ინტერესები', budget: 'დღიური ბიუჯეტი (USD)', next: 'შემდეგი კითხვა', back: 'უკან', make: 'მარშრუტის შექმნა', picks: 'შენი პირველი დღის არჩევანი' }, ru: { title: 'Создайте поездку для себя', lead: 'Расскажите Compass о своих интересах — он составит реалистичный маршрут.', country: 'Страна', city: 'Город', interests: 'Выберите интересы', budget: 'Дневной бюджет (USD)', next: 'Следующий вопрос', back: 'Назад', make: 'Создать маршрут', picks: 'Идеи на первый день' }, es: { title: 'Crea un viaje a tu medida', lead: 'Cuéntale a Compass qué te gusta y preparará un día realista.', country: 'País', city: 'Ciudad', interests: 'Elige tus intereses', budget: 'Presupuesto diario (USD)', next: 'Siguiente', back: 'Atrás', make: 'Crear mi ruta', picks: 'Ideas para tu primer día' } } as const

export default function Planner({ language, onTripCreated }: Props) {
  const t = labels[language]
  const [step, setStep] = useState(0)
  const [interests, setInterests] = useState<string[]>(['Food'])
  const [budget, setBudget] = useState(80)
  const [created, setCreated] = useState(false)
  const [added, setAdded] = useState<string[]>([])
  const estimated = interests.reduce((total, interest) => total + costs[interest], 0) + 12
  const toggle = (interest: string) => setInterests(current => current.includes(interest) ? current.filter(value => value !== interest) : [...current, interest])
  const submit = (event: FormEvent) => { event.preventDefault(); setCreated(true); onTripCreated?.() }
  return <div className="planner-content detailed-planner"><span className="eyebrow">COMPASS TRIP BUILDER</span><h2>{t.title}</h2><p className="planner-lead">{t.lead}</p><div className="stepper">{['Place & budget', 'Your interests', ...choices.map(([question]) => question)].map((label, index) => <span className={index === step ? 'current' : index < step ? 'done' : ''} key={label}><b>{index + 1}</b>{label}</span>)}</div><form onSubmit={submit}>{step === 0 && <div className="destination-row"><label>{t.country}<input defaultValue="Georgia" required /></label><label>{t.city}<input defaultValue="Tbilisi" required /></label><label>{t.budget}<input type="number" value={budget} onChange={event => setBudget(Number(event.target.value))} min="0" required /></label></div>}{step === 1 && <fieldset><legend>{t.interests}</legend><div className="choice-row">{Object.keys(costs).map(interest => <button type="button" className={interests.includes(interest) ? 'selected' : ''} onClick={() => toggle(interest)} key={interest}>{interest}</button>)}</div></fieldset>}{step >= 2 && <fieldset className="question-card"><legend>Question {step - 1} of {choices.length}</legend><h3>{choices[step - 2][0]}</h3><div className="choice-row">{choices[step - 2][1].map(choice => <button type="button" className="selected" key={choice}>{choice}</button>)}</div></fieldset>}{interests.length > 0 && (step === 1 || step === 0) && budget < estimated && <div className="budget-warning"><strong>${budget}/day is tight for this combination.</strong><p>These interests in Tbilisi are estimated at about ${estimated}/day.</p><div><button type="button" onClick={() => setInterests(current => current.filter(interest => interest !== 'Nightlife' && interest !== 'Wellness'))}>Choose lower-cost activities</button><button type="button" onClick={() => setBudget(estimated)}>Adjust budget to ${estimated}</button><button type="button" onClick={() => setBudget(Math.max(45, estimated - 20))}>Try a nearby budget area</button></div></div>}<div className="planner-actions">{step > 0 && <button type="button" className="back-button" onClick={() => setStep(step - 1)}>{t.back}</button>}{step < choices.length + 1 ? <button type="button" className="build-route" onClick={() => setStep(step + 1)}>{t.next} ↗</button> : <button className="build-route" type="submit">{t.make} ↗</button>}</div></form>{created && <section className="place-suggestions"><span className="eyebrow">{t.picks}</span><div className="planner-result"><strong>Narikala Fortress → Fabrika Courtyard → Abanotubani Baths</strong><span>Balanced walking route · adjusted for your interests</span><button type="button" onClick={() => setAdded(['Narikala Fortress', 'Fabrika Courtyard', 'Abanotubani Baths'])}>{added.length ? `✓ ${added.length} stops added` : 'Add this route'}</button></div></section>}</div>
}
