import { FormEvent, useEffect, useState } from 'react'
import axios from 'axios'
import MapView from './pages/MapView'
import Planner from './pages/Planner'
import './theme.css'
import './fixes.css'
import './darkfix.css'

type Section = 'home' | 'plan' | 'map' | 'visited' | 'friends'
type AuthPage = 'login' | 'register'
type Language = 'en' | 'ka' | 'ru' | 'es'
type Message = { id: number; role: 'assistant' | 'user'; text: string }

const stops = [
  { time: '10:00', name: 'Narikala Fortress', note: 'Walk and viewpoint' },
  { time: '13:00', name: 'Fabrika Courtyard', note: 'Lunch reservation' },
  { time: '17:30', name: 'Abanotubani Baths', note: 'Booked - 90 minutes' },
]
const ideas = [
  ['Tbilisi old town', 'Culture and food', 'https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=900&q=80'],
  ['Kazbegi mountains', 'Nature day', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80'],
  ['Kakheti wine road', 'Weekend escape', 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=80'],
]

function Landing({ go }: { go: (path: string) => void }) {
  return <main className="landing-page"><nav className="landing-nav"><button className="brand" onClick={() => go('/')}><span className="brand-mark">T</span><span>travelconnect</span></button><button className="text-button" onClick={() => go('/login')}>Log in</button></nav><section className="landing-hero"><div><span className="eyebrow">YOUR TRAVEL, YOUR PEOPLE</span><h1>Plan together.<br /><em>Travel deeper.</em></h1><p>Turn shared ideas into thoughtful routes, memorable places, and stories worth bringing home.</p><div className="landing-actions"><button className="primary-action" onClick={() => go('/login')}>Log in <span>↗</span></button><button className="outline-action" onClick={() => go('/register')}>Create an account</button></div></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=1200&q=85" alt="Friends sharing a meal while travelling" /><div className="floating-note"><strong>Today in Tbilisi</strong><span>3 stops · 4.2 km · with friends</span></div></div></section><section className="landing-features"><div><span>01</span><h3>Compass AI</h3><p>Shape a day around your pace, taste, and real budget.</p></div><div><span>02</span><h3>Routes that breathe</h3><p>See every stop and the path between them, at a glance.</p></div><div><span>03</span><h3>Travel in company</h3><p>Share plans, discover communities, and decide together.</p></div></section></main>
}

function AuthPage({ mode, onSuccess, go }: { mode: AuthPage; onSuccess: () => void; go: (path: string) => void }) {
  const register = mode === 'register'
  const [values, setValues] = useState({ name: '', email: '', password: '', confirm: '', terms: false })
  const [errors, setErrors] = useState<Record<string, string>>({})
  const update = (key: string, value: string | boolean) => setValues(current => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => {
    event.preventDefault()
    const next: Record<string, string> = {}
    if (register && !values.name.trim()) next.name = 'Enter your name.'
    if (!values.email.match(/^\S+@\S+\.\S+$/)) next.email = 'Enter a valid email address.'
    if (values.password.length < 8) next.password = 'Use at least 8 characters.'
    if (register && values.confirm !== values.password) next.confirm = 'Passwords do not match.'
    if (register && !values.terms) next.terms = 'Accept the terms to continue.'
    setErrors(next)
    if (!Object.keys(next).length) { localStorage.setItem('travelconnect-auth', 'true'); onSuccess() }
  }
  return <main className="auth-page"><button className="brand auth-brand" onClick={() => go('/')}><span className="brand-mark">T</span><span>travelconnect</span></button><form className="auth-card" onSubmit={submit}><span className="eyebrow">{register ? 'JOIN THE NETWORK' : 'WELCOME BACK'}</span><h1>{register ? 'Make room for more journeys.' : 'Pick up where you left off.'}</h1><p>{register ? 'Your next shared route starts here.' : 'Your routes, people, and places are waiting.'}</p>{register && <label>Name<input value={values.name} onChange={e => update('name', e.target.value)} placeholder="Alex Morgan" />{errors.name && <small className="field-error">{errors.name}</small>}</label>}<label>Email<input type="email" value={values.email} onChange={e => update('email', e.target.value)} placeholder="you@example.com" />{errors.email && <small className="field-error">{errors.email}</small>}</label><label>Password<input type="password" value={values.password} onChange={e => update('password', e.target.value)} placeholder="At least 8 characters" />{errors.password && <small className="field-error">{errors.password}</small>}</label>{register && <label>Confirm password<input type="password" value={values.confirm} onChange={e => update('confirm', e.target.value)} placeholder="Repeat your password" />{errors.confirm && <small className="field-error">{errors.confirm}</small>}</label>}{register && <label className="terms"><input type="checkbox" checked={values.terms} onChange={e => update('terms', e.target.checked)} /> I agree to the terms and community guidelines</label>}{errors.terms && <small className="field-error">{errors.terms}</small>}{!register && <button type="button" className="forgot">Forgot password?</button>}<button className="primary-action auth-submit" type="submit">{register ? 'Create account' : 'Log in'} <span>↗</span></button><p className="auth-switch">{register ? 'Already have an account?' : 'New to TravelConnect?'} <button type="button" onClick={() => go(register ? '/login' : '/register')}>{register ? 'Log in' : 'Register'}</button></p></form></main>
}

function App() {
  const [path, setPath] = useState(window.location.pathname)
  const [dark, setDark] = useState(true)
  const [language, setLanguage] = useState<Language>('en')
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [destinations, setDestinations] = useState(['Narikala Fortress', 'Fabrika Courtyard', 'Abanotubani Baths'])
  const [community, setCommunity] = useState('')
  const [chatMessages, setChatMessages] = useState<Message[]>([{ id: 1, role: 'assistant', text: 'I am Compass. What kind of trip would make you happy today?' }])
  const authenticated = localStorage.getItem('travelconnect-auth') === 'true'
  const section = (['home', 'plan', 'map', 'visited', 'friends'] as Section[]).includes(path.slice(1) as Section) ? path.slice(1) as Section : 'home'
  const go = (next: string) => { window.history.pushState({}, '', next); setPath(next) }
  useEffect(() => { const handlePop = () => setPath(window.location.pathname); window.addEventListener('popstate', handlePop); return () => window.removeEventListener('popstate', handlePop) }, [])
  if (!authenticated && path !== '/login' && path !== '/register') return <Landing go={go} />
  if (!authenticated) return <AuthPage mode={path.slice(1) as AuthPage} go={go} onSuccess={() => go('/')} />
  const logout = () => { localStorage.removeItem('travelconnect-auth'); go('/') }
  const send = async (event: FormEvent) => { event.preventDefault(); if (!input.trim()) return; const next = [...chatMessages, { id: Date.now(), role: 'user' as const, text: input }]; setChatMessages(next); setInput(''); setLoading(true); try { const response = await axios.post('/api/ai/chat', { messages: next.map(({ role, text }) => ({ role, text })) }); setChatMessages(current => [...current, { id: Date.now(), role: 'assistant', text: response.data.reply }]) } catch { setChatMessages(current => [...current, { id: Date.now(), role: 'assistant', text: 'Connect Gemini in backend/.env for live travel answers.' }]) } finally { setLoading(false) } }
  const home = <main className="dashboard fuller-home"><aside className="left-rail"><section className="profile-card"><div className="cover" /><div className="profile-avatar">AM</div><h2>Alex Morgan</h2><p>Tbilisi, Georgia</p><div className="profile-stats"><button><strong>12</strong><span>places</span></button><button><strong>31</strong><span>saved</span></button><button><strong>48</strong><span>friends</span></button></div></section></aside><section className="home-center"><section className="hero-home"><span className="eyebrow">PLAN BETTER, TRAVEL DEEPER</span><h1>Your next great day starts here.</h1><p>Build a route around what you want to eat, see, feel and remember.</p><button onClick={() => go('/plan')}>Start planning</button><button className="secondary" onClick={() => go('/map')}>Open my route</button></section><section className="chat-panel compact-chat"><div className="chat-header"><div><span className="eyebrow">COMPASS AI</span><h2>Ask your travel companion</h2></div></div><div className="messages">{chatMessages.map(message => <div className={`message ${message.role}`} key={message.id}><div className="message-icon">{message.role === 'assistant' ? 'AI' : 'AM'}</div><div>{message.text}</div></div>)}{loading && <div className="message assistant"><div className="message-icon">AI</div><div>Thinking...</div></div>}</div><form className="composer" onSubmit={send}><input value={input} onChange={event => setInput(event.target.value)} placeholder="Ask for an itinerary, food, hotels, or ideas" /><button type="submit">Ask Compass</button></form></section><section className="discover-section"><span className="eyebrow">EXPLORE GEORGIA</span><h2>Good ideas for your next free day</h2><div className="destination-grid">{ideas.map(([name, tag, image]) => <article className="destination-card" key={name}><img src={image} alt={name} /><span>{tag}</span><h3>{name}</h3><button onClick={() => go('/plan')}>Build around this ↗</button></article>)}</div></section></section><aside className="right-rail"><section className="rail-card"><span className="eyebrow">NEXT UP</span>{stops.map(stop => <div className="trip-row" key={stop.name}><span className="route-time">{stop.time}</span><div><strong>{stop.name}</strong><small>{stop.note}</small></div></div>)}</section></aside></main>
  const route = <section className="route-page"><div className="route-sidebar"><span className="eyebrow">TUESDAY, 12 SEPTEMBER</span><h1>Your Tbilisi route</h1><p className="route-summary">{destinations.length} stops · 4.2 km · walking and taxi</p><label className="add-destination">Add a destination<select onChange={event => event.target.value && !destinations.includes(event.target.value) && setDestinations([...destinations, event.target.value])} defaultValue=""><option value="">Choose a place</option><option>Mtatsminda Park</option><option>National Botanical Garden</option><option>Dry Bridge Market</option></select></label><div className="itinerary-list">{destinations.map((name, index) => <article key={name}><time>{['10:00', '13:00', '17:30', '20:00'][index] || 'Any time'}</time><div><span className="timeline-dot">{index + 1}</span><h3>{name}</h3><p>{index === 0 ? 'Walk and viewpoint' : 'Added to your route'}</p><button onClick={() => setDestinations(destinations.filter(destination => destination !== name))}>Remove</button></div></article>)}</div></div><div className="route-map"><MapView showRoute /></div></section>
  const visited = <section className="public-history"><span className="eyebrow">PUBLIC TRAVEL HISTORY</span><h1>Places Alex has visited</h1><p>Choose a route to see the places and path connected to it.</p><div className="history-layout"><div className="visited-list">{[['Tbilisi essentials', '3 places · September 12', 5], ['A slow Sunday', '2 places · August 28', 4], ['Georgia north', '4 places · July 14', 5]].map(([name, detail, stars]) => <article className="visited-place" key={name as string}><div className="visit-photo" /><div><span>COMPLETED ROUTE</span><h3>{name}</h3><p>{detail} · {'★'.repeat(stars as number)}</p><button onClick={() => go('/map')}>Open route ↗</button></div></article>)}</div><div className="mini-map"><MapView showRoute /></div></div></section>
  const friends = <section className="friends-page"><aside className="discord-rail"><b>TC</b><button>+</button><button>G</button><button>B</button></aside><section className="friend-list"><div className="friend-search">Find a traveler</div><p>ONLINE - 3</p>{['Nino - planning Batumi', 'Luka - in Tbilisi', 'Mariam - exploring Spain'].map(friend => <button onClick={() => setCommunity(friend)} key={friend}><span className="online-avatar">{friend[0]}</span><span>{friend}</span></button>)}<p>COMMUNITIES</p>{['Georgia food lovers', 'Weekend hikers'].map(channel => <button onClick={() => setCommunity(channel)} key={channel}><span className="online-avatar">#</span><span>{channel}</span></button>)}</section><section className="friend-content"><span className="eyebrow">FRIEND ACTIVITY</span><h1>Travel together, even apart.</h1><div className="activity-card"><div className="online-avatar">N</div><div><h3>Nino is planning a Batumi weekend</h3><p>2 days · beach · local food</p><button onClick={() => setCommunity('Nino - planning Batumi')}>Open plan</button></div></div><div className="community-panel"><span className="eyebrow">{community ? 'OPEN COMMUNITY' : 'YOUR TRAVEL NETWORK'}</span><h2>{community || 'Pick a friend or channel'}</h2><div className="thread"><p><b>Nino</b> I found a tiny place near the beach.</p><p><b>You</b> Add it to the shared route?</p></div><form className="community-composer" onSubmit={event => event.preventDefault()}><input placeholder="Write a message" /><button type="submit">Send</button></form></div></section></section>
  const content = section === 'plan' ? <section className="full-page-panel planner-page"><Planner language={language} onTripCreated={() => go('/map')} /></section> : section === 'map' ? route : section === 'visited' ? visited : section === 'friends' ? friends : home
  return <div className={`app-shell ${dark ? 'dark' : 'light'}`}><header className="topbar"><button className="brand" onClick={() => go('/')}><span className="brand-mark">T</span><span>travelconnect</span></button><nav className="primary-nav">{([['Home', 'home'], ['Plan trip', 'plan'], ['My route', 'map'], ['Visited', 'visited'], ['Friends', 'friends']] as [string, Section][]).map(([label, value]) => <button className={section === value ? 'nav-item active' : 'nav-item'} onClick={() => go(`/${value}`)} key={value}>{label}</button>)}</nav><div className="topbar-actions"><button className="theme-toggle" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? '☼' : '☾'}</button><select className="language-select" value={language} onChange={event => setLanguage(event.target.value as Language)}><option value="en">English</option><option value="ka">Georgian</option><option value="ru">Russian</option><option value="es">Spanish</option></select><button className="logout-button" onClick={logout}>Log out</button><button className="avatar">AM</button></div></header>{content}<footer className="site-footer"><div><b>travelconnect</b><p>Plan together. Travel deeper.</p></div><div><a>About</a><a>Safety</a><a>Help center</a><a>Privacy</a></div><small>© 2026 TravelConnect</small></footer></div>
}

export default App
