import { FormEvent, useState } from 'react'
import axios from 'axios'
import MapView from './pages/MapView'
import Planner from './pages/Planner'
import './theme.css'
import './fixes.css'
import './darkfix.css'
type Section='home'|'plan'|'map'|'visited'|'friends'; type Language='en'|'ka'|'ru'|'es'; type Message={id:number;role:'assistant'|'user';text:string}
const stops=[{time:'10:00',name:'Narikala Fortress',note:'Walk and viewpoint'},{time:'13:00',name:'Fabrika Courtyard',note:'Lunch reservation'},{time:'17:30',name:'Abanotubani Baths',note:'Booked - 90 minutes'}]
const ideas=[['Tbilisi old town','Culture and food','https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=900&q=80'],['Kazbegi mountains','Nature day','https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80'],['Kakheti wine road','Weekend escape','https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=80']]
function App(){
 const [section,setSection]=useState<Section>('home'),[dark,setDark]=useState(true),[language,setLanguage]=useState<Language>('en'),[input,setInput]=useState(''),[loading,setLoading]=useState(false),[destinations,setDestinations]=useState<string[]>(['Narikala Fortress','Fabrika Courtyard','Abanotubani Baths']),[account,setAccount]=useState(false),[community,setCommunity]=useState(''),[reminders,setReminders]=useState(false)
 const [messages,setMessages]=useState<Message[]>([{id:1,role:'assistant',text:'I am Compass. What kind of trip would make you happy today?'}])
 const send=async(e:FormEvent)=>{e.preventDefault();if(!input.trim())return;const next=[...messages,{id:Date.now(),role:'user' as const,text:input}];setMessages(next);setInput('');setLoading(true);try{const r=await axios.post('/api/ai/chat',{messages:next.map(({role,text})=>({role,text}))});setMessages(c=>[...c,{id:Date.now(),role:'assistant',text:r.data.reply}])}catch{setMessages(c=>[...c,{id:Date.now(),role:'assistant',text:'Connect Gemini in backend/.env for live travel answers.'}])}finally{setLoading(false)}}
 const remindersOn=async()=>{if('Notification'in window&&await Notification.requestPermission()==='granted'){setReminders(true);new Notification('TravelConnect reminders enabled',{body:'Your next stop is Narikala Fortress at 10:00.'})}}
 const home=<main className="dashboard fuller-home"><aside className="left-rail"><section className="profile-card"><div className="cover"/><div className="profile-avatar">AM</div><h2>Alex Morgan</h2><p>Tbilisi, Georgia</p><div className="profile-stats"><button><strong>12</strong><span>places</span></button><button><strong>31</strong><span>saved</span></button><button><strong>48</strong><span>friends</span></button></div><button className="view-profile" onClick={()=>setAccount(true)}>Edit profile</button></section></aside><section className="home-center"><section className="hero-home"><span className="eyebrow">PLAN BETTER, TRAVEL DEEPER</span><h1>Your next great day starts here.</h1><p>Build a route around what you want to eat, see, feel and remember.</p><button onClick={()=>setSection('plan')}>Start planning</button><button className="secondary" onClick={()=>setSection('map')}>Open my route</button></section><section className="chat-panel compact-chat"><div className="chat-header"><div><span className="eyebrow">COMPASS AI</span><h2>Ask your travel companion</h2></div></div><div className="messages">{messages.map(m=><div className={`message ${m.role}`} key={m.id}><div className="message-icon">{m.role==='assistant'?'AI':'AM'}</div><div>{m.text}</div></div>)}{loading&&<div className="message assistant"><div className="message-icon">AI</div><div>Thinking...</div></div>}</div><form className="composer" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask for an itinerary, food, hotels, or ideas"/><button aria-label="Ask Compass" type="submit">Ask Compass</button></form></section><section className="discover-section"><div className="section-title"><div><span className="eyebrow">EXPLORE GEORGIA</span><h2>Good ideas for your next free day</h2></div></div><div className="destination-grid">{ideas.map(([name,tag,img])=><article className="destination-card" key={name}><img src={img} alt={name}/><span>{tag}</span><h3>{name}</h3><button onClick={()=>setSection('plan')}>Build a day here</button></article>)}</div></section></section><aside className="right-rail"><section className="rail-card trip-list"><div className="card-title"><h3>Today on your trip</h3><button onClick={()=>setSection('map')}>View route</button></div>{stops.map(s=><button className="trip-row" onClick={()=>setSection('map')} key={s.time}><span className="route-time">{s.time}</span><span><strong>{s.name}</strong><small>{s.note}</small></span></button>)}</section><section className="rail-card"><p className="card-label">REMINDERS</p><h3>{reminders?'Reminders enabled':'Never miss a booking'}</h3><p>Get alerts before every planned stop.</p><button onClick={remindersOn}>{reminders?'Enabled':'Enable reminders'}</button></section></aside></main>
 const route=<section className="route-page"><div className="route-sidebar"><span className="eyebrow">TUESDAY, 12 SEPTEMBER</span><h1>Your Tbilisi route</h1><p className="route-summary">{destinations.length} stops · 4.2 km · walking and taxi</p><button className="reminder-button" onClick={remindersOn}>{reminders?'Reminders enabled':'Enable trip reminders'}</button><label className="add-destination">Add a destination<select onChange={e=>e.target.value&&!destinations.includes(e.target.value)&&setDestinations([...destinations,e.target.value])} defaultValue=""><option value="">Choose a place</option><option>Mtatsminda Park</option><option>National Botanical Garden</option><option>Dry Bridge Market</option></select></label><div className="itinerary-list">{destinations.map((name,i)=><article key={name}><time>{['10:00','13:00','17:30','20:00','21:00'][i]||'Any time'}</time><div><span className="timeline-dot">{i+1}</span><h3>{name}</h3><p>{i===0?'Walk and viewpoint':'Added to your route'}</p><button onClick={()=>setDestinations(destinations.filter(d=>d!==name))}>Remove</button></div></article>)}</div></div><div className="route-map"><MapView showRoute/></div></section>
 const visited=<section className="public-history"><span className="eyebrow">PUBLIC TRAVEL HISTORY</span><h1>Places Alex has visited</h1><p>Places, ratings and photos you choose to make visible.</p><div className="history-layout"><div className="visited-list">{[['Stamba Hotel','Coffee and design',5],['Shavi Lomi','Georgian restaurant',4],['Chronicle of Georgia','Landmark',5]].map(([name,type,stars])=><article className="visited-place" key={name as string}><div className="visit-photo"/><div><span>{type}</span><h3>{name}</h3><p>{'★'.repeat(stars as number)}{'☆'.repeat(5-(stars as number))}</p><button>View visit details</button></div></article>)}</div><div className="mini-map"><MapView showRoute/></div></div><section className="complete-trip"><div><span className="eyebrow">JUST FINISHED A TRIP?</span><h2>Share it with your travel network.</h2><p>Rate places and add travel photos.</p></div><button onClick={()=>setAccount(true)}>Add review and photos</button></section></section>
 const friends=<section className="friends-page"><aside className="discord-rail"><b>TC</b><button>+</button><button>G</button><button>B</button></aside><section className="friend-list"><div className="friend-search">Find a traveler</div><p>ONLINE - 3</p>{['Nino - planning Batumi','Luka - in Tbilisi','Mariam - exploring Spain'].map(f=><button onClick={()=>setCommunity(f)} key={f}><span className="online-avatar">{f[0]}</span><span>{f}</span><i>...</i></button>)}<p>COMMUNITIES</p>{['Georgia food lovers','Weekend hikers'].map(f=><button onClick={()=>setCommunity(f)} key={f}><span className="online-avatar">#</span><span>{f}</span></button>)}</section><section className="friend-content"><span className="eyebrow">FRIEND ACTIVITY</span><h1>Travel together, even apart.</h1><div className="activity-card"><div className="online-avatar">N</div><div><h3>Nino is planning a Batumi weekend</h3><p>2 days · beach · local food</p><button onClick={()=>setCommunity('Nino - planning Batumi')}>Open plan</button></div></div>{community&&<div className="community-panel"><button onClick={()=>setCommunity('')}>x</button><span className="eyebrow">OPEN COMMUNITY</span><h2>{community}</h2><p>Chat, share routes, and decide where to go together.</p><input placeholder="Write a message"/><button>Post message</button></div>}</section></section>
 const content=section==='plan'?<section className="full-page-panel planner-page"><Planner language={language} onTripCreated={()=>setSection('map')}/></section>:section==='map'?route:section==='visited'?visited:section==='friends'?friends:home
 return <div className={`app-shell ${dark?'dark':'light'}`}><header className="topbar"><button className="brand" onClick={()=>setSection('home')}><span className="brand-mark">T</span><span>travelconnect</span></button><nav className="primary-nav">{([['Home','home'],['Plan trip','plan'],['My route','map'],['Visited','visited'],['Friends','friends']]as[string,Section][]).map(([l,v])=><button className={section===v?'nav-item active':'nav-item'} onClick={()=>setSection(v)} key={v}>{l}</button>)}</nav><div className="topbar-actions"><button className="theme-toggle" onClick={()=>setDark(!dark)}>{dark?'Light':'Dark'}</button><select className="language-select" value={language} onChange={e=>setLanguage(e.target.value as Language)}><option value="en">English</option><option value="ka">Georgian</option><option value="ru">Russian</option><option value="es">Spanish</option></select><button className="new-trip" onClick={()=>setAccount(true)}>Create account</button><button className="avatar">AM</button></div></header>{content}<footer className="site-footer"><div><b>travelconnect</b><p>Plan together. Travel deeper.</p></div><div><a>About</a><a>Safety</a><a>Help center</a><a>Privacy</a></div><small>© 2026 TravelConnect</small></footer>{account&&<div className="review-modal"><form onSubmit={e=>{e.preventDefault();setAccount(false)}}><button type="button" className="close" onClick={()=>setAccount(false)}>x</button><span className="eyebrow">JOIN TRAVELCONNECT</span><h2>Create your account</h2><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@example.com"/></label><label>I am a<select><option>Traveler</option><option>Travel business</option><option>Hotel or accommodation</option><option>Restaurant or attraction</option></select></label><label>Password<input required type="password"/></label><button type="submit">Create account</button></form></div>}</div>
}
export default App
